DROP_FILETYPEID: [
    1643, 1644, # file: 4. passive investors (like institutions) to update their beneficial ownership of over 5% but less than 20% of a public company's stock
    631, # file: SCHDULE 13G/A report changes in beneficial ownership of a reporting company's equity securities by corporate insiders. 
    634, # file 144: NOTICE OF PROPOSED SALE OF SECURITIES
    259, 260, # file 8k
    695, # DFAN14A
    632, # 3
    612, 613, 615, 616, 656, 642, # SC
    880, 636, # S (registration statement)
    713, 687, 690, 192,
    697, 715, 701,  # 14A
    622, 620, # 13F
    637, # 5
    160, # 10-Q
    142, # 10-K
    178, # ARS
    813, # 8-A12B
    682, # FWP
    257, # 6-K
    177, # CIQ type: AR. earnings release or earnings report
    184, # CIQ type: ER. earnings release or earnings report
    ]